# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-east-1

nodeGroups:
  - name: ng-2
    instanceType: m5.large
    spot: true
    desiredCapacity: 3
    ssh: 
      publicKeyName: kubernetes   #replace this with our keypair in aws